program Frontend;

uses
  Vcl.Forms,
  View.Base in 'src\view\bases\View.Base.pas' {FrmBase},
  View.Base.Master in 'src\view\bases\View.Base.Master.pas' {FrmBaseMaster},
  View.Base.Master.Grid in 'src\view\bases\View.Base.Master.Grid.pas' {FrmBaseMasterGrid},
  View.Base.Master.Workflow in 'src\view\bases\View.Base.Master.Workflow.pas' {FrmBaseMasterWorkflow},
  View.Register.User.Grid in 'src\view\Registers\Users\View.Register.User.Grid.pas' {FrmRegUserGrid},
  Controller.Base.Entity.Intf in 'src\controller\bases\Interfaces\Controller.Base.Entity.Intf.pas',
  Controller.Base.Entity in 'src\controller\bases\Controller.Base.Entity.pas',
  Utils.Types in 'src\Utils\Utils.Types.pas',
  Service.Entity.Details.Intf in 'src\model\services\interfaces\Service.Entity.Details.Intf.pas',
  View.Main in 'src\view\View.Main.pas' {FrmMain},
  Controller.Entity.User in 'src\controller\Controller.Entity.User.pas',
  Service.Entity.User in 'src\model\services\Service.Entity.User.pas',
  Handle.Details.User in 'src\controller\handle\Handle.Details.User.pas',
  Factory.Entity.Intf in 'src\controller\factory\bases\Interface\Factory.Entity.Intf.pas',
  Factory.Interfaces in 'src\controller\factory\Factory.Interfaces.pas',
  Factory.User in 'src\controller\factory\Factory.User.pas',
  View.Base.Fundo in 'src\view\bases\View.Base.Fundo.pas' {FrmFundo},
  Factory.Interfaces.Intf in 'src\controller\factory\Interface\Factory.Interfaces.Intf.pas',
  Factory.User.Intf in 'src\controller\factory\Interface\Factory.User.Intf.pas',
  Handle.Details.Intf in 'src\controller\handle\bases\interface\Handle.Details.Intf.pas',
  Handle.Base.Details in 'src\controller\handle\bases\Handle.Base.Details.pas',
  Factory.Base.Entity in 'src\controller\factory\bases\Factory.Base.Entity.pas',
  Service.Base.Entity.Details in 'src\model\services\bases\Service.Base.Entity.Details.pas',
  View.Register.Member.Grid in 'src\view\Registers\Members\View.Register.Member.Grid.pas' {FrmRegMemberGrid},
  View.Login in 'src\view\Authentications\View.Login.pas' {FrmLogin},
  Config.URL in 'src\config\Config.URL.pas',
  Providers.Session in 'src\model\providers\Providers.Session.pas',
  Providers.Token in 'src\model\providers\Providers.Token.pas',
  Service.Authentications.Login.Intf in 'src\model\services\Authentications\Interfaces\Service.Authentications.Login.Intf.pas',
  Service.Authentications.Login in 'src\model\services\Authentications\Service.Authentications.Login.pas',
  Providers.Request.Intf in 'src\model\providers\Interfaces\Providers.Request.Intf.pas',
  Providers.Request in 'src\model\providers\Providers.Request.pas',
  Providers.Response.Intf in 'src\model\providers\Interfaces\Providers.Response.Intf.pas',
  View.Register.User.Workflow in 'src\view\Registers\Users\View.Register.User.Workflow.pas' {FrmRegUserWorkflow},
  View.Base.Master.Step in 'src\view\bases\View.Base.Master.Step.pas' {FrmBaseMasterStep},
  View.Register.User.Data.Step in 'src\view\Registers\Users\View.Register.User.Data.Step.pas' {FrmStepDataUser},
  View.Base.Master.Details in 'src\view\bases\View.Base.Master.Details.pas' {TFrmBaseMasterDetails},
  View.Register.User.Details in 'src\view\Registers\Users\View.Register.User.Details.pas' {FrmRegUserDetails},
  Components.Button in 'src\view\components\Components.Button.pas' {FrmButton: TFrame},
  View.Base.Popup in 'src\view\bases\View.Base.Popup.pas' {FrmBasePopup},
  View.Base.Popup.Message in 'src\view\bases\View.Base.Popup.Message.pas' {FrmBaseMessage},
  View.Popup.Success.Message in 'src\view\Popups\View.Popup.Success.Message.pas' {FrmSuccessMessage},
  View.Popup.Delete in 'src\view\Popups\View.Popup.Delete.pas' {FrmPopupDelete},
  View.Popup.Question.Message in 'src\view\Popups\View.Popup.Question.Message.pas' {FrmQuestionMessage},
  View.Register.User.Password.Step in 'src\view\Registers\Users\View.Register.User.Password.Step.pas' {FrmStepPasswordUser},
  Factory.Members in 'src\controller\factory\Factory.Members.pas',
  Factory.Member.Intf in 'src\controller\factory\Interface\Factory.Member.Intf.pas',
  Service.Entity.Member in 'src\model\services\Service.Entity.Member.pas',
  Handle.Details.Member in 'src\controller\handle\Handle.Details.Member.pas',
  Controller.Entity.Member in 'src\controller\Controller.Entity.Member.pas',
  View.Register.Member.Workflow in 'src\view\Registers\Members\View.Register.Member.Workflow.pas' {FrmRegMemberWorkflow},
  View.Register.Campaign.Grid in 'src\view\Registers\Campaigns\View.Register.Campaign.Grid.pas' {FrmRegCampaignGrid},
  Factory.Campaigns in 'src\controller\factory\Factory.Campaigns.pas',
  Factory.Campaign.Intf in 'src\controller\factory\Interface\Factory.Campaign.Intf.pas',
  Handle.Details.Campaign in 'src\controller\handle\Handle.Details.Campaign.pas',
  Service.Entity.Campaign in 'src\model\services\Service.Entity.Campaign.pas',
  Controller.Entity.Campaign in 'src\controller\Controller.Entity.Campaign.pas',
  View.Reports.Master in 'src\view\Reports\View.Reports.Master.pas' {FrmMasterReports},
  Controller.Entity.Report in 'src\controller\Controller.Entity.Report.pas',
  Factory.Reports in 'src\controller\factory\Factory.Reports.pas',
  Factory.Report.Intf in 'src\controller\factory\Interface\Factory.Report.Intf.pas',
  Factory.Transactions in 'src\controller\factory\Factory.Transactions.pas',
  Controller.Entity.Transaction in 'src\controller\Controller.Entity.Transaction.pas',
  Handle.Details.Transaction in 'src\controller\handle\Handle.Details.Transaction.pas',
  Factory.Transaction.Intf in 'src\controller\factory\Interface\Factory.Transaction.Intf.pas',
  Service.Entity.Transaction in 'src\model\services\Service.Entity.Transaction.pas',
  View.Register.Transaction.Grid in 'src\view\Registers\Transactions\View.Register.Transaction.Grid.pas' {FrmRegTransactionGrid},
  View.Register.Transaction.Data.Step in 'src\view\Registers\Transactions\View.Register.Transaction.Data.Step.pas' {FrmStepDataTransaction},
  View.Register.Member.Data.Step in 'src\view\Registers\Members\View.Register.Member.Data.Step.pas' {FrmStepDataMember},
  View.Register.Campaign.Data.Step in 'src\view\Registers\Campaigns\View.Register.Campaign.Data.Step.pas' {FrmStepDataCampaign},
  View.Register.Campaign.Workflow in 'src\view\Registers\Campaigns\View.Register.Campaign.Workflow.pas' {FrmRegCampaignWorkflow},
  View.Register.Transaction.Workflow in 'src\view\Registers\Transactions\View.Register.Transaction.Workflow.pas' {FrmRegTransactionWorkflow},
  View.Register.Member.Details in 'src\view\Registers\Members\View.Register.Member.Details.pas' {FrmRegMemberDetails},
  View.Register.Campaign.Details in 'src\view\Registers\Campaigns\View.Register.Campaign.Details.pas' {FrmRegCampaignDetails},
  View.Register.Transaction.Details in 'src\view\Registers\Transactions\View.Register.Transaction.Details.pas' {FrmRegTransactionDetails},
  View.Register.Church.Grid in 'src\view\Registers\Church\View.Register.Church.Grid.pas' {FrmRegChurchGrid},
  Factory.Churchs in 'src\controller\factory\Factory.Churchs.pas',
  Factory.Church.Intf in 'src\controller\factory\Interface\Factory.Church.Intf.pas',
  Handle.Details.Church in 'src\controller\handle\Handle.Details.Church.pas',
  Service.Entity.Church in 'src\model\services\Service.Entity.Church.pas',
  Controller.Entity.Church in 'src\controller\Controller.Entity.Church.pas',
  View.Register.Church.Data.Step in 'src\view\Registers\Church\View.Register.Church.Data.Step.pas' {FrmStepDataChurch},
  View.Register.Church.Workflow in 'src\view\Registers\Church\View.Register.Church.Workflow.pas' {FrmRegChurchWorkflow},
  View.Register.Church.Details in 'src\view\Registers\Church\View.Register.Church.Details.pas' {FrmRegChurchDetails},
  View.Register.Member.Transaction.Data.Step in 'src\view\Registers\Members\View.Register.Member.Transaction.Data.Step.pas' {FrmStepDataMemberTransaction},
  Service.Detail.Members.Trasaction in 'src\model\services\Service.Detail.Members.Trasaction.pas',
  View.Register.Campaign.Transaction.Data.Step in 'src\view\Registers\Campaigns\View.Register.Campaign.Transaction.Data.Step.pas' {FrmStepDataCampaignTransaction},
  Service.Detail.Campaign.Trasaction in 'src\model\services\Service.Detail.Campaign.Trasaction.pas',
  View.Reports.Settings.Master in 'src\view\Reports\View.Reports.Settings.Master.pas' {FrmReportSettingsMaster},
  View.Reports.Settings.Withdrawals in 'src\view\Reports\View.Reports.Settings.Withdrawals.pas' {FrmReportWithdrawals},
  View.Reports.Settings.Campaigns in 'src\view\Reports\View.Reports.Settings.Campaigns.pas' {FrmReportCampaigns},
  View.Reports.Settings.CashFlow in 'src\view\Reports\View.Reports.Settings.CashFlow.pas' {FrmReportCashFlow},
  View.Reports.Settings.Tithes in 'src\view\Reports\View.Reports.Settings.Tithes.pas' {FrmReportTithes},
  View.Reports.Settings.Entries in 'src\view\Reports\View.Reports.Settings.Entries.pas' {FrmReportEntries},
  View.Master.Dashboard in 'src\view\Registers\Dashboard\View.Master.Dashboard.pas' {FrmMasterDashboard};

{$R *.res}

begin
  Application.Initialize;
{$IFDEF Debug}
  ReportMemoryLeaksOnShutdown := True;
{$ENDIF}
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFrmMain, FrmMain);
  Application.Run;
end.
